name: Node.js CI
permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Jest tests
          path: ./test-results/junit.xml
          reporter: jest-junit
          fail-on-error: true
